config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" },
                     skip: [:registrations]
  authenticate :user do
    root to: 'dashboards#index', as: :authenticated_root
    get 'dashboard', to: 'dashboards#index', as: 'dashboard'
    get 'reports', to: 'reports#index', as: 'reports'
    get 'budget_bar', to: 'dashboards#budget_bar', defaults: { format: :js }, as: 'budget_bar'
    post 'search', to: 'dashboards#search', defaults: { format: :js }

    # For call list management
    patch 'call_lists/reorder_call_list', to: 'call_lists#reorder_call_list', as: 'reorder_call_list', defaults: { format: :js }
    patch 'call_lists/clear_current_user_call_list', to: 'call_lists#clear_current_user_call_list', as: 'clear_current_user_call_list', defaults: { format: :js }
    patch 'call_lists/add_patient/:id', to: 'call_lists#add_patient', as: 'add_patient', defaults: { format: :js }
    patch 'call_lists/remove_patient/:id', to: 'call_lists#remove_patient', as: 'remove_patient', defaults: { format: :js }

    # User REST routes and searching
    post 'users/search', to: 'users#search', as: 'users_search', defaults: { format: :js }
    resources :users, only: [:new, :create, :index, :edit, :update]

    # For user management
    patch 'users/:id/change_role_to_admin', to: 'users#change_role_to_admin', as: 'change_role_to_admin'
    patch 'users/:id/change_role_to_data_volunteer', to: 'users#change_role_to_data_volunteer', as: 'change_role_to_data_volunteer'
    patch 'users/:id/change_role_to_cm', to: 'users#change_role_to_cm', as: 'change_role_to_cm'
    post 'users/:id/toggle_disabled', to: 'users#toggle_disabled', as: 'toggle_disabled'

    # Patient routes
    # /patients/:id/edit
    # /patients/:id/calls
    # /patients/:id/notes
    # /patients/:id/external_pledges
    resources :patients,
              only: [ :create, :edit, :update, :index, :destroy ] do
      member do
        get :download, as: 'generate_pledge'
      end
      resources :calls,
                only: [ :create, :destroy, :new ]
      resources :notes,
                only: [ :create, :update ]
      resources :external_pledges,
                only: [ :create, :update, :destroy ]
    end

    get 'reports/:timeframe', to: 'reports#report', as: 'patients_report'

    get 'patients/:patient_id/submit_pledge', to: 'patients#pledge', as: 'submit_pledge'

    get 'data_entry', to: 'patients#data_entry', as: 'data_entry' # temporary
    post 'data_entry', to: 'patients#data_entry_create', as: 'data_entry_create' # temporary

    resources :accountants, only: [:index, :edit]
    post 'accountant/search', to: 'accountants#search', defaults: { format: :js }

    resources :lines, only: [:new, :create]
    post 'clinicfinder', to: 'clinicfinders#search', defaults: { format: :js }, as: 'clinicfinder_search'
    resources :clinics, only: [:index, :create, :update, :new, :destroy, :edit]
    resources :configs, only: [:index, :create, :update]
    resources :events, only: [:index]
  end

  # Auth routes
  root :to => redirect('/users/sign_in')
  as :user do
    get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put '/users' => 'devise/registrations#update', as: 'registration'
  end
end

app/controllers/clinicfinders_controller.rb
# Controller for use with clinic_finder gem; locates nearest clinic
# based on certain info.
class ClinicfindersController < ApplicationController
  def search
    return head :bad_request if params[:zip].blank?

    # Clinics intentionally excluded from ClinicFinder are assigned the zip 99999.
    # e.g. so a fund can have an 'OTHER CLINIC' catchall.
    excluded_zip = '99999'

    # Get all clinics except those with invalid zip codes.
    clinic_finder = ClinicFinder::Locator.new(
      Clinic.where(:zip.nin => [nil, '', excluded_zip]),
      gestational_age: (params[:gestation].to_i || 0),
      naf_only: params[:naf_only] == '1',
      medicaid_only: params[:medicaid_only] == '1'
    )

    @nearest = clinic_finder.locate_nearest_clinics params[:zip]
    @cheapest = nil # clinic_finder.locate_cheapest_clinic
    respond_to { |format| format.js }
  end
end

app/helpers/clinicfinders_helper.rb
# Fields used in the result table will vary, so...
module ClinicfindersHelper
  def parse_clinicfinder_field(clinic, field)
    case field
    when :location
      "#{clinic.city}, #{clinic.state}"
    when :distance
      "#{clinic[field].round(2)} miles"
    when :cost
      number_to_currency clinic[field], precision: 0
    else
      clinic[field]
    end
  end
end

app/views/clinicfinders/_result_table.html.erb
<h3><%= title %></h3>
<table class="table">
  <thead>
    <% clinic_fields.each do |label| %>
      <th><%= label.to_s.humanize %></th>
    <% end %>
  </thead>
  <tbody>
    <% clinics.each do |clinic| %>
      <tr>
        <% clinic_fields.each do |field| %>
          <td><%= parse_clinicfinder_field clinic, field %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clinicfinders/_search_form.html.erb
<div class='col-sm-12'>
  <h5 class='clinic-finder-expand'>
    Clinic Locator Assistant
    <span class='glyphicon glyphicon-plus-sign pull-right'></span>
  </h5>

  <div class='col-sm-12 hide' id='clinic-finder-search-form'>
    <h6>A tool for sorting clinics by cost and distance.</h6>

    <%= bootstrap_form_tag url: clinicfinder_search_path, remote: true do |f| %>
      <div class="row">
        <div class="col-sm-6 info-form-left">
          <%= f.text_field :zip, label: "Patient's ZIP code" %>
          <%= f.check_box :naf_only, label: 'Show only NAF clinics' %>
          <%= f.check_box :medicaid_only, label: 'Show only Medicaid clinics' %>
        </div>

        <div class="col-sm-6 info-form-right">
          This is an experimental feature.
          <%#= f.select :gestation, weeks_options, label: "Patient's approx. gestation at appt" %>
        </div>
      </div>

      <div class="row">
        <div class='col-sm-6'>
          <%= f.submit "Search clinics", class: "btn btn-primary" %>
        </div>    
      </div>
    <% end %>
  </div>

  <div class='col-sm-12' id='clinic-finder-results'></div>
</div>

app/views/clinicfinders/search.js.erb
$('#clinic-finder-results').empty().hide();

<% if @nearest&.any? %>
  $("#clinic-finder-results").append("<%= escape_javascript(render partial: 'clinicfinders/result_table', locals: { title: 'Nearest Clinics', clinic_fields: [:name, :location, :accepts_naf, :distance], clinics: @nearest }) %>");
<% end %>

<% if @cheapest&.any? %>
  $("#clinic-finder-results").append("<%= escape_javascript(render partial: 'clinicfinders/result_table', locals: { title: 'Most Affordable Clinics', clinic_fields: [:name, :cost], clinics: @cheapest }) %>");
<% end %>

$("#clinic-finder-results").slideDown('fast');