config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" },
                     skip: [:registrations]
  authenticate :user do
    root to: 'dashboards#index', as: :authenticated_root
    get 'dashboard', to: 'dashboards#index', as: 'dashboard'
    get 'reports', to: 'reports#index', as: 'reports'
    get 'budget_bar', to: 'dashboards#budget_bar', defaults: { format: :js }, as: 'budget_bar'
    post 'search', to: 'dashboards#search', defaults: { format: :js }

    # For call list management
    patch 'call_lists/reorder_call_list', to: 'call_lists#reorder_call_list', as: 'reorder_call_list', defaults: { format: :js }
    patch 'call_lists/clear_current_user_call_list', to: 'call_lists#clear_current_user_call_list', as: 'clear_current_user_call_list', defaults: { format: :js }
    patch 'call_lists/add_patient/:id', to: 'call_lists#add_patient', as: 'add_patient', defaults: { format: :js }
    patch 'call_lists/remove_patient/:id', to: 'call_lists#remove_patient', as: 'remove_patient', defaults: { format: :js }

    # User REST routes and searching
    post 'users/search', to: 'users#search', as: 'users_search', defaults: { format: :js }
    resources :users, only: [:new, :create, :index, :edit, :update]

    # For user management
    patch 'users/:id/change_role_to_admin', to: 'users#change_role_to_admin', as: 'change_role_to_admin'
    patch 'users/:id/change_role_to_data_volunteer', to: 'users#change_role_to_data_volunteer', as: 'change_role_to_data_volunteer'
    patch 'users/:id/change_role_to_cm', to: 'users#change_role_to_cm', as: 'change_role_to_cm'
    post 'users/:id/toggle_disabled', to: 'users#toggle_disabled', as: 'toggle_disabled'

    # Patient routes
    # /patients/:id/edit
    # /patients/:id/calls
    # /patients/:id/notes
    # /patients/:id/external_pledges
    resources :patients,
              only: [ :create, :edit, :update, :index, :destroy ] do
      member do
        get :download, as: 'generate_pledge'
      end
      resources :calls,
                only: [ :create, :destroy, :new ]
      resources :notes,
                only: [ :create, :update ]
      resources :external_pledges,
                only: [ :create, :update, :destroy ]
    end

    get 'reports/:timeframe', to: 'reports#report', as: 'patients_report'

    get 'patients/:patient_id/submit_pledge', to: 'patients#pledge', as: 'submit_pledge'

    get 'data_entry', to: 'patients#data_entry', as: 'data_entry' # temporary
    post 'data_entry', to: 'patients#data_entry_create', as: 'data_entry_create' # temporary

    resources :accountants, only: [:index, :edit]
    post 'accountant/search', to: 'accountants#search', defaults: { format: :js }

    resources :lines, only: [:new, :create]
    post 'clinicfinder', to: 'clinicfinders#search', defaults: { format: :js }, as: 'clinicfinder_search'
    resources :clinics, only: [:index, :create, :update, :new, :destroy, :edit]
    resources :configs, only: [:index, :create, :update]
    resources :events, only: [:index]
  end

  # Auth routes
  root :to => redirect('/users/sign_in')
  as :user do
    get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put '/users' => 'devise/registrations#update', as: 'registration'
  end
end

app/models/user.rb
# Object representing a case manager.
# Fields are all devise settings; most of the methods relate to call list mgmt.
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Userstamp::User
  include Mongoid::History::Trackable
  extend Enumerize

  include UserSearchable
  include CallListable
  track_history on: fields.keys + [:updated_by_id],
                  version_field: :version,
                  track_create: true,
                  track_update: true,
                  track_destroy: true

  after_create :send_account_created_email, if: :persisted?

  # Devise modules
  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :trackable,
          :validatable,
          :lockable,
          :timeoutable,
          :omniauthable, omniauth_providers: [:google_oauth2]
  # :rememberable
  # :confirmable

  # Callbacks
  after_update :send_password_change_email, if: :needs_password_change_email?

  # Relationships
  has_and_belongs_to_many :patients, inverse_of: :users

  # Fields
  # Non-devise generated
  field :name, type: String
  field :line, type: String
  field :role

  enumerize :role, in: [:cm, :admin, :data_volunteer], predicates: true
  field :call_order, type: Array # Manipulated by the call list controller

  ## Database authenticatable
  field :email,              type: String, default: ''
  field :encrypted_password, type: String, default: ''

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  # field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  field :failed_attempts, type: Integer, default: 0
  # field :unlock_token,    type: String
  field :locked_at,       type: Time

  # An extra hard shutoff field for when a fund wants to shut off a user acct.
  # We call this disabling in the app, but users/CMs see this as 'Lock/Unlock'.
  # We do this because Devise calls a temporary account shutoff because of too
  # many failed attempts an account lock.
  field :disabled_by_fund, type: Boolean, default: false

  # Validations
  # email presence validated through Devise
  validates :name, presence: true
  validate :secure_password

  TIME_BEFORE_DISABLED_BY_FUND = 9.months

  def secure_password
    return true if password.nil?
    pc = verify_password_complexity
    if pc == false
      errors.add :password, 'Password must include at least one lowercase ' \
                            'letter, one uppercase letter, and one digit. ' \
                            "Forbidden words include #{FUND} and password."
    end
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.find_by email: data['email']

    user
  end

  def toggle_disabled_by_fund
    # Since toggle skips callbacks...
    update disabled_by_fund: !disabled_by_fund
  end

  def self.disable_inactive_users
    cutoff_date = Time.zone.now - TIME_BEFORE_DISABLED_BY_FUND
    inactive_has_logged_in = where(:role.nin => [:admin],
                                   :current_sign_in_at.lt => cutoff_date)
    inactive_no_logins = where(:role.nin => [:admin],
                               :current_sign_in_at => nil,
                               :created_at.lt => cutoff_date)
    [inactive_no_logins, inactive_has_logged_in].each do |set|
      set.update disabled_by_fund: true
    end
  end

  def admin?
    role == 'admin'
  end

  def allowed_data_access?
    admin? || data_volunteer?
  end

  private

  def verify_password_complexity
    return false unless password.length >= 8 # length at least 8
    return false if (password =~ /[a-z]/).nil? # at least one lowercase
    return false if (password =~ /[A-Z]/).nil? # at least one uppercase
    return false if (password =~ /[0-9]/).nil? # at least one digit
    # Make sure no bad words are in there
    return false unless password.downcase[/(password|#{FUND})/].nil?
    true
  end

  def needs_password_change_email?
    encrypted_password_changed? && persisted?
  end

  def send_password_change_email
    # @user = User.find(id)
    UserMailer.password_changed(id).deliver_now
  end

  def send_account_created_email
    UserMailer.account_created(id).deliver_now
  end
end

app/controllers/dashboards_controller.rb
# Controller for rendering the home view and patient search.
class DashboardsController < ApplicationController
  include LinesHelper
  include BudgetBarCalculable

  before_action :pick_line_if_not_set, only: [:index, :search]

  def index
    @urgent_patients = Patient.urgent_patients(current_line)
  end

  def search
    @results = Patient.search params[:search],
                              [current_line.try(:to_sym) || lines]

    @patient = Patient.new
    @today = Time.zone.today.to_date
    @phone = searched_for_phone?(params[:search]) ? params[:search] : ''
    @name = searched_for_name?(params[:search]) ? params[:search] : ''

    respond_to { |format| format.js }
  end

  def budget_bar
    render partial: 'dashboards/budget_bar',
           locals: budget_bar_calculations(current_line)
  end

  private

  def searched_for_phone?(query)
    !/[a-z]/i.match query
  end

  def searched_for_name?(query)
    /[a-z]/i.match query
  end

  def pick_line_if_not_set
    redirect_to new_line_path if session[:line].blank?
  end
end

app/helpers/dashboards_helper.rb
# Convenience methods consumed in the dashboards controller index view
module DashboardsHelper
  def week_range(date: Time.zone.now, start_day: :monday)
    week_start = date.beginning_of_week start_day
    week_end = date.end_of_week start_day
    week_start_string = l week_start, format: '%B %-d'
    week_end_string = if week_start.month == week_end.month
                        l week_end, format: '%-d'
                      else
                        l week_end, format: '%B %-d'
                      end
    "#{week_start_string} - #{week_end_string}"
  end

  def voicemail_options
    enum_text = { not_specified: t('dashboard.helpers.voicemail_options.not_specified'),
                  no: t('dashboard.helpers.voicemail_options.no'),
                  yes: t('dashboard.helpers.voicemail_options.yes') }
    Patient.voicemail_preference
           .values
           .map { |option| option.to_sym }
           .map { |option| [enum_text[option], option.to_sym] }
  end

  def remove_from_call_list_glyphicon
    safe_join [
      tag(:span, class: ['glyphicon', 'glyphicon-remove'],
                 aria: { hidden: true }),
      tag(:span, class: ['sr-only'], text: 'Remove call')
    ]
  end

  def call_glyphicon
    safe_join [
      tag(:span, class: ['glyphicon', 'glyphicon-earphone'],
                 aria: { hidden: true }),
      tag(:span, class: ['sr-only'], text: 'Call')
    ]
  end
end

app/views/dashboards/_activity_feed.html.erb
<div id='activity_feed' class='margin-bottom'>
  <h1 class='border-bottom title'>Activity on this line</h1>

  <div id="activity_feed_content">
    <%= render_async events_path, nonce: content_security_policy_script_nonce %>
  </div>
</div>

app/views/dashboards/_activity_log.html.erb
<div id='activity_log' class='margin-bottom'>
  <h1 class='border-bottom title'>
    <%= t 'dashboard.activity_log.label', current_line: current_line %>
  </h1>

  <div id="activity_log_content">
    <%= render_async events_path, nonce: content_security_policy_script_nonce, 'data-turbolinks-track': 'reload' %>
  </div>
</div>

app/views/dashboards/_budget_bar.html.erb
<div class="col-sm-12" id='budget-bar-content'>
  <div class="row">
    <div class="progress" id='budget-progress-bar'>
      <% expenditures.each_pair do |type, patient_hashes| %>
        <% patient_hashes.each do |patient| %>
          <div class="progress-bar <%= progress_bar_color type %> expenditure-block" style='<%= progress_bar_width patient[:fund_pledge], limit %>' role='progressbar'>
            <div data-toggle='popover' data-content='<%= budget_bar_expenditure_content(patient) %>' data-placement='bottom' data-html='true' class='expenditure-item'>
              <%= number_to_currency patient[:fund_pledge], precision: 0 %> <%= type %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="row" id='budget-report'>
      <% expenditures.each_pair do |type, patient_hashes| %>
        <div class="col-sm-4">
          <%= number_to_currency(expenditures[type].map { |h| h[:fund_pledge] }.inject(:+) || 0, precision: 0)  %> <%= type  %> (<%= expenditures[type].count %> patients)
        </div>
      <% end %>
      <%# TODO Commenting out until the config is ready %>
      <!-- 
      <div class="col-sm-4">
        <%= number_to_currency(budget_bar_remaining(expenditures, limit), precision: 0) %> remaining
      </div>
      -->
    </div>
  </div>
</div>

<script nonce='<%= content_security_policy_script_nonce %>'>
  $(function () {
    $('.expenditure-item').popover()
  })
</script>

app/views/dashboards/_modal.html.erb
<div class="modal fade new-call" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- dynamically load modal-content -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/dashboards/_overview.html.erb
<div id="overview" class="margin-bottom">
  <h1 class="border-bottom title">
    <%= t 'dashboard.overview.week_of', week_range: week_range %>
    <%= dashboard_table_content_tooltip_shell "budget_bar" %>
  </h1>

  <div id="budget_bar">
    <%= render_async budget_bar_path, nonce: content_security_policy_script_nonce, 'data-turbolinks-track': 'reload' %>
  </div>
</div>

app/views/dashboards/_search_form.html.erb
<div id="search_form" class="margin-bottom">
  <h1 class="border-bottom title">
    <%= t 'dashboard.search.header' %>
  </h1>

  <%= bootstrap_form_tag url: '/search', remote: true, layout: :inline do |p| %>
    <%= p.text_field :search, placeholder: t('dashboard.search.input_placeholder'), hide_label: true, class: 'search_form_input' %>
    <%= p.button class: 'btn btn-primary', title: t('common.search') do %>
      <i class="glyphicon glyphicon-search"></i>
    <% end %>
  <% end %>

  <div id="search_results_shell"></div>
</div>

app/views/dashboards/_table_content.html.erb
<!-- locals: title, table_type (for div id and tbody div id), pregnancies, sortable, autosortable -->

<div id="<%= table_type %>" class="margin-bottom">
  <h1 class="border-bottom title">
    <%= title %>
    <%= dashboard_table_content_tooltip_shell table_type %>    
  </h1>

  <table class="table border-side" id="<%= table_type %>_table">
    <thead>
      <tr>
        <% if local_assigns[:sortable] %>
          <th><!-- handle --></th>
        <% end %>
        <th><%= t 'common.phone' %></th>
        <th><%= t 'common.name' %></th>
        <th><%= t 'common.weeks_along_short' %></th>
        <%= th_autosortable t('common.status'), 'string', local_assigns %>
        <%= th_autosortable t('common.appointment_date_short'), 'string', local_assigns %>
        <th><%= t 'common.notes' %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody id="<%= table_type %>_content">
      <% patients.each do |patient| %>
        <tr class="patient-data" id="<%= patient.id %>">
          <% if local_assigns[:sortable] %>
            <td class="handle"><span class="glyphicon glyphicon-move"></span></td>
          <% end %>
          <td class="pt-spacer"><%= patient.primary_phone_display %></td>
          <td class="pt-spacer"><%= link_to patient.name, edit_patient_path(patient) %></td>
          <td class="pt-spacer"><%= patient.last_menstrual_period_display_short %></td>
          <td><%= patient.status %></td>
          <td><%= patient.appointment_date_display %></td>
          <td><%= patient.most_recent_note_display_text %> <%= plus_sign_glyphicon(patient.most_recent_note) %></td>
          <% if table_type == 'completed_calls' || table_type == 'urgent_patients' %>
            <td class="blank-td"></td>
          <% else %>
            <% if current_user.patient_ids.include?(patient.id) %>
              <td><%= link_to remove_from_call_list_glyphicon, remove_patient_path(patient), method: :patch, data: { confirm: t('dashboard.table_content.remove_from_call_list_confirm', name: patient.name) },  remote: true %></td>
            <% else %>
              <td><%= link_to t('common.add'), add_patient_path(patient), method: :patch, remote: true %></td>
            <% end %>
          <% end %>
          <td>
            <%= link_to call_glyphicon,
                        new_patient_call_path(patient),
                        class: "call_button call-#{patient.primary_phone_display}",
                        remote: true %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if table_type == 'call_list' && current_user.patients.count.nonzero? %>
    <%= link_to t('dashboard.table_content.clear_call_list'),
                clear_current_user_call_list_path,
                class: "pull-right text-danger",
                data: { confirm: t('dashboard.table_content.clear_call_list_confirm') },
                method: :patch,
                remote: true %>
  <% end %>
</div>

app/views/dashboards/index.html.erb
<script>
  $(function () {
    $('[data-toggle="popover"]').popover()
  })
</script>

<div class="row">
  <div class="col-sm-12">
    <%= render partial: 'dashboards/overview' %>
    <%= render partial: 'dashboards/search_form' %>
    <%= render partial: 'dashboards/table_content',
               locals: { title: t('dashboard.partial_titles.call_list'),
                         table_type: 'call_list',
                         patients: current_user.ordered_patients(current_line),
                         sortable: true,
                         autosortable: true } %>
    <%= render partial: 'dashboards/table_content',
               locals: { title: t('dashboard.partial_titles.completed_calls'),
                         table_type: 'completed_calls',
                         patients: current_user.recently_called_patients(current_line),
                         autosortable: true } %>
    <%= render partial: 'dashboards/table_content',
               locals: { title: t('dashboard.partial_titles.urgent_cases'),
                         table_type: 'urgent_cases',
                         patients: @urgent_patients,
                         autosortable: true } %>
    <%= render partial: 'dashboards/modal' %>
    <%= render partial: 'dashboards/activity_log' %>
  </div>
</div>

app/views/dashboards/search.js.erb
$('#search_results_shell').empty();
$("#search_results_shell").append("<%= escape_javascript(render partial: 'patients/new_patient', locals: { patient: @patient, name: @name, phone: @phone, today: @today }) %>");

<% if @results.any? %>
  $("#search_results_shell").append("<%= escape_javascript(render partial: 'dashboards/table_content', locals: { title: t('dashboard.partial_titles.search_results'), table_type: 'search_results', patients: @results } ) %>");
    $(function () {
    $('[data-toggle="popover"]').popover()
  })
<% end %>