config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" },
                     skip: [:registrations]
  authenticate :user do
    root to: 'dashboards#index', as: :authenticated_root
    get 'dashboard', to: 'dashboards#index', as: 'dashboard'
    get 'reports', to: 'reports#index', as: 'reports'
    get 'budget_bar', to: 'dashboards#budget_bar', defaults: { format: :js }, as: 'budget_bar'
    post 'search', to: 'dashboards#search', defaults: { format: :js }

    # For call list management
    patch 'call_lists/reorder_call_list', to: 'call_lists#reorder_call_list', as: 'reorder_call_list', defaults: { format: :js }
    patch 'call_lists/clear_current_user_call_list', to: 'call_lists#clear_current_user_call_list', as: 'clear_current_user_call_list', defaults: { format: :js }
    patch 'call_lists/add_patient/:id', to: 'call_lists#add_patient', as: 'add_patient', defaults: { format: :js }
    patch 'call_lists/remove_patient/:id', to: 'call_lists#remove_patient', as: 'remove_patient', defaults: { format: :js }

    # User REST routes and searching
    post 'users/search', to: 'users#search', as: 'users_search', defaults: { format: :js }
    resources :users, only: [:new, :create, :index, :edit, :update]

    # For user management
    patch 'users/:id/change_role_to_admin', to: 'users#change_role_to_admin', as: 'change_role_to_admin'
    patch 'users/:id/change_role_to_data_volunteer', to: 'users#change_role_to_data_volunteer', as: 'change_role_to_data_volunteer'
    patch 'users/:id/change_role_to_cm', to: 'users#change_role_to_cm', as: 'change_role_to_cm'
    post 'users/:id/toggle_disabled', to: 'users#toggle_disabled', as: 'toggle_disabled'

    # Patient routes
    # /patients/:id/edit
    # /patients/:id/calls
    # /patients/:id/notes
    # /patients/:id/external_pledges
    resources :patients,
              only: [ :create, :edit, :update, :index, :destroy ] do
      member do
        get :download, as: 'generate_pledge'
      end
      resources :calls,
                only: [ :create, :destroy, :new ]
      resources :notes,
                only: [ :create, :update ]
      resources :external_pledges,
                only: [ :create, :update, :destroy ]
    end

    get 'reports/:timeframe', to: 'reports#report', as: 'patients_report'

    get 'patients/:patient_id/submit_pledge', to: 'patients#pledge', as: 'submit_pledge'

    get 'data_entry', to: 'patients#data_entry', as: 'data_entry' # temporary
    post 'data_entry', to: 'patients#data_entry_create', as: 'data_entry_create' # temporary

    resources :accountants, only: [:index, :edit]
    post 'accountant/search', to: 'accountants#search', defaults: { format: :js }

    resources :lines, only: [:new, :create]
    post 'clinicfinder', to: 'clinicfinders#search', defaults: { format: :js }, as: 'clinicfinder_search'
    resources :clinics, only: [:index, :create, :update, :new, :destroy, :edit]
    resources :configs, only: [:index, :create, :update]
    resources :events, only: [:index]
  end

  # Auth routes
  root :to => redirect('/users/sign_in')
  as :user do
    get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put '/users' => 'devise/registrations#update', as: 'registration'
  end
end

app/controllers/reports_controller.rb
# Controller for automatically generated service reporting across lines.
class ReportsController < ApplicationController
  before_action :confirm_data_access, only: [:index]
  before_action :confirm_data_access_async, only: [:report]

  def index; end

  def report
    case params[:timeframe]
    when 'weekly'
      @report = Reports::LineSummary.generate(1.week.ago, Date.today)
      render partial: "patient_report", locals: { report: @report, lines: LINES, timeframe: params[:timeframe] }

    when 'monthly'
      @report = Reports::LineSummary.generate(1.month.ago, Date.today)
      render partial: "patient_report", locals: { report: @report, lines: LINES, timeframe: params[:timeframe] }

    when 'yearly'
      @report = Reports::LineSummary.generate(1.year.ago, Date.today)
      render partial: "patient_report", locals: { report: @report, lines: LINES, timeframe: params[:timeframe] }

    when 'fulfillment'
      @reports = Rerports::Fulfillmentt.generate
      render partial: "patient_report", locals: { report: @report, lines: LINES, timeframe: params[:timeframe] }

    else
      head :not_acceptable
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_patient_report.html.erb
<%= javascript_tag nonce: content_security_policy_script_nonce do %>
  $(function() {
    var report = <%= report.to_json.html_safe %>
    var lines = (<%= lines.to_json.html_safe %>)
    lines = lines.map(function(line) {
      return report[line]
    });

    var chart = c3.generate({
      transition: {
        duration: 2000
      },
      bindto: '#chart-<%= timeframe %>_report',
      data: {
          json: lines,
          type: 'bar',
          keys: {
            x: 'name',
            value: ['patients_contacted', 'new_patients_contacted', 'pledges_sent'],
          }
      },
      bar: {
          width: {
              ratio: 0.5
          }
      },
      axis: {
        x: {
          type: 'category'
        }
      }
    });
  });
<% end %>

<div class="report-section">
  <% case timeframe
  when 'weekly' %>
  <h2 class="border-bottom">Week of <%= week_range %></h2>
  <% when 'monthly' %>
  <h2 class="border-bottom">Past 30 days</h2>
  <% when 'yearly' %>
  <h2 class="border-bottom">Year to date</h2>
  <% end %>
  <div class="row">
    <div id='chart-<%= timeframe %>_report'></div>
    <% lines.each do |line| %>
      <div class="col-sm-4">
        <h3><%= link_to line, '#', class: 'line-header' %></h3>

        <p>Patients contacted: <strong><%= report[line.to_sym][:patients_contacted] %></strong></p>
        <p>New patients contacted: <strong><%= report[line.to_sym][:new_patients_contacted] %></strong></p>
        <p>Pledges sent: <strong><%= report[line.to_sym][:pledges_sent] %></strong></p>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/index.html.erb
<h1><strong><%= FUND %> Data Center</strong></h1>
<div class="row">
  <h4 class="col-sm-8"><strong>Budget bar, design TK</strong></h4>
</div>
<!-- UNCOMMENT WHEN BUDGET BAR IS READY
<div id="budget_bar">
  <div class="progress"></div>
  <div class="progress-bar progress-bar-striped"</div>
</div>
 -->
<%= render_async patients_report_path(timeframe: 'weekly'), nonce: content_security_policy_script_nonce %>
<%= render_async patients_report_path(timeframe: 'monthly'), nonce: content_security_policy_script_nonce %>
<%= render_async patients_report_path(timeframe: 'yearly'), nonce: content_security_policy_script_nonce %>
<%#= render partial: 'reports/fulfillment' -- Not functional yet %>